; version.asm
;
; Auto-generated by ZXVersion.exe
; On 16 Feb 2020 at 20:08

BuildNo                 macro()
                        db "8"
mend

BuildNoValue            equ "8"
BuildNoWidth            equ 0 + FW8



BuildDate               macro()
                        db "16 Feb 2020"
mend

BuildDateValue          equ "16 Feb 2020"
BuildDateWidth          equ 0 + FW1 + FW6 + FWSpace + FWF + FWe + FWb + FWSpace + FW2 + FW0 + FW2 + FW0



BuildTime               macro()
                        db "20:08"
mend

BuildTimeValue          equ "20:08"
BuildTimeWidth          equ 0 + FW2 + FW0 + FWColon + FW0 + FW8



BuildTimeSecs           macro()
                        db "20:08:30"
mend

BuildTimeSecsValue      equ "20:08:30"
BuildTimeSecsWidth      equ 0 + FW2 + FW0 + FWColon + FW0 + FW8 + FWColon + FW3 + FW0
