; version.asm
;
; Auto-generated by ZXVersion.exe
; On 19 Jan 2020 at 12:01

BuildNo                 macro()
                        db "3"
mend

BuildNoValue            equ "3"
BuildNoWidth            equ 0 + FW3



BuildDate               macro()
                        db "19 Jan 2020"
mend

BuildDateValue          equ "19 Jan 2020"
BuildDateWidth          equ 0 + FW1 + FW9 + FWSpace + FWJ + FWa + FWn + FWSpace + FW2 + FW0 + FW2 + FW0



BuildTime               macro()
                        db "12:01"
mend

BuildTimeValue          equ "12:01"
BuildTimeWidth          equ 0 + FW1 + FW2 + FWColon + FW0 + FW1



BuildTimeSecs           macro()
                        db "12:01:46"
mend

BuildTimeSecsValue      equ "12:01:46"
BuildTimeSecsWidth      equ 0 + FW1 + FW2 + FWColon + FW0 + FW1 + FWColon + FW4 + FW6
