; version.asm
;
; Auto-generated by ZXVersion.exe
; On 06 Feb 2020 at 12:36

BuildNo                 macro()
                        db "7"
mend

BuildNoValue            equ "7"
BuildNoWidth            equ 0 + FW7



BuildDate               macro()
                        db "06 Feb 2020"
mend

BuildDateValue          equ "06 Feb 2020"
BuildDateWidth          equ 0 + FW0 + FW6 + FWSpace + FWF + FWe + FWb + FWSpace + FW2 + FW0 + FW2 + FW0



BuildTime               macro()
                        db "12:36"
mend

BuildTimeValue          equ "12:36"
BuildTimeWidth          equ 0 + FW1 + FW2 + FWColon + FW3 + FW6



BuildTimeSecs           macro()
                        db "12:36:11"
mend

BuildTimeSecsValue      equ "12:36:11"
BuildTimeSecsWidth      equ 0 + FW1 + FW2 + FWColon + FW3 + FW6 + FWColon + FW1 + FW1
